// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List_Api.DAL;

namespace To_Do_List_Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210828053508_addingTaskTable")]
    partial class addingTaskTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("To_Do_List_Api.Models.Dept", b =>
                {
                    b.Property<int>("deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("deptid");

                    b.ToTable("Dept");

                    b.HasData(
                        new
                        {
                            deptid = 1,
                            dname = "Ms.",
                            location = "Amelia"
                        });
                });

            modelBuilder.Entity("To_Do_List_Api.Models.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
